### ISSUE TITLE
Couldn't send spi message: Message too long

### ISSUE THREAD

**Issue by rjo** [uraimo/MCP3008.swift#3]
Trying to run the example on a Pi 3B yields this error.

**Comment by uraimo** [comment]
Try this https://github.com/lukevanhorn/Lepton3/issues/4
More: https://forums.raspberrypi.com/viewtopic.php?p=837140

It's an issue with the SPI buffer size, no idea if they changed the default recently.

**Comment by rjo** [comment]
I had a feeling I should not have upgraded the OS on this board. Thanks.
